### ISSUE TITLE
site dinokiki.com error of memory limit

### ISSUE THREAD

**Issue by baricio** [giuliacardieri/dinokiki#12]
the site dinokiki.com doesnt' work. Error of memory limit

![dinokiki com](https://user-images.githubusercontent.com/1015059/31520032-e006db84-af7a-11e7-9310-429d3d2cb9d4.png)

**Comment by giuliacardieri** [comment]
Hey @baricio, thanks for creating the issue.
That's a server problem. I have a free plan and need to upgrade to a better one.
I can't do it right now but will do it soon :)
This issue is not related to coding.
