### ISSUE TITLE
Create docker for developer environment

### ISSUE THREAD

**Issue by baricio** [giuliacardieri/dinokiki#13]
I suggest create a docker environment for easy up project.
If you want, i can do it.

**Comment by giuliacardieri** [comment]
hey @baricio,
I'm trying to understand what docker is, why it would fix the issue with the server and why I should use it.
Dinokiki is a fun project for me, I don't want to make it too complicated or complex.
Could you tell me why I should user Docker?
This project is something I like to try new technologies. I think I don't want to change its structure and add something new like Docker.

**Comment by baricio** [comment]
hey @giuliacardieri
your project is very funny. I want help you. Docker not change your project at all :wink:. With a docker turn more easy run project in developer machine. No need install Apache, PHP, MySQL because each user has a different OS, different versions of PHP, MySQL and different settings. Docker turn unique environment. If you want try new technologies, sooner or later you will use docker. But is only a suggestion. :grinning:

**Comment by giuliacardieri** [comment]
That seems nice @baricio  :D 
I'll study a little bit about docker and answer your pull request on the next few days. Thanks for explaining it to me.
