### ISSUE TITLE
Modal text is broken on smaller screens - About

### ISSUE THREAD

**Issue by giuliacardieri** [giuliacardieri/dinokiki#4]
The text on all modals on About page are broken for smaller screens (>768px).
_
O texto nos modais da página About ficam quebrados em telas menores.
![screen shot 2017-10-06 at 00 18 45](https://user-images.githubusercontent.com/6403755/31261685-120840fe-aa2c-11e7-9ceb-ff2493eac332.png)

**Comment by gustavoper** [comment]
I think we should use a dialog plugin (using jquery or similar). But we must change a few things in that page. What do you think?

--

Acho que poderiamos usar um plugin de "dialog" (jquery ou similar). Só no caso teriamos que mudar bastante coisa principalmente nessa tela (hahaha). O que acha?

**Comment by giuliacardieri** [comment]
solved by pull request #17
