### ISSUE TITLE
Cannot share results on Facebook - Game

### ISSUE THREAD

**Issue by giuliacardieri** [giuliacardieri/dinokiki#5]
Facebook updated their API and now the results from the game cannot be shared. Find how to solve this problem.
_ 
Facebook atualizou a API e agora os resultados do jogo não podem ser compartilhados. Descobrir como resolver isso.
![screen shot 2017-10-06 at 00 20 49](https://user-images.githubusercontent.com/6403755/31261729-67416bfe-aa2c-11e7-9a5b-099c7d49e3e0.png)

**Comment by dongido001** [comment]
Hi @giuliacardieri , would love to take on this

**Comment by giuliacardieri** [comment]
Hey @dongido001, go ahead :D

**Comment by djiwandou** [comment]
Hi all, how's the status of this issue @giuliacardieri @dongido001 ? ✌️

**Comment by dongido001** [comment]
Didn't look at, feel free to hop on @djwandou

**Comment by giuliacardieri** [comment]
@djiwandou hey! Sorry, this issue is a bit old. The website's stack has been updated since 2017. I'll close this issue and work on opening new issues (yay hacktoberfest!!) the next week.

**Comment by djiwandou** [comment]
Thanks, let's go to hacktoberfest 😄 💪   @giuliacardieri @dongido001
