### ISSUE TITLE
Make Your Own Dinokiki link should be different - Nav

### ISSUE THREAD

**Issue by giuliacardieri** [giuliacardieri/dinokiki#6]
Make Your Own Dinokiki link at the navigation should be different or have a detail indicating that it will open in a new tab.
_ 
O link Make Your Own Dinokiki deveria ser diferente ou ter um detalhe indicando que vai abrir em uma nova guia.

**Comment by gustavoper** [comment]
[I think it should be like that.](https://imgur.com/a/J0KXH) 

It's ready to PR just say the word!

**Comment by giuliacardieri** [comment]
hey @gustavoper, that seems nice :)
If you want to do the PR go ahead.
