### ISSUE TITLE
Add some application/config files to .gitignore

### ISSUE THREAD

**Issue by gustavoper** [giuliacardieri/dinokiki#9]
Hi there! Your project is pretty good, gratz!

But you should add some application/config files to .gitignore and create sample files: 

``application\config\config.php``
``application\config\database.php``

This is necessary to avoid some problems like expose your database information, server folder structure and so on.

**Comment by giuliacardieri** [comment]
thanks for the help :D 
I'll fix this soon.

**Comment by gustavoper** [comment]
I did these changes in my working repo (also updated README). If you want it we can merge.

---

Eu fiz as alterações no meu repo, dá uma olhada. Se você preferir podemos fazer o merge via PR.
